### ISSUE TITLE
this might be not proper place but severe freezing issue. need help

### ISSUE THREAD

**Issue by AkagiShiroe** [theimpulson/fire_kernel_asus_msm8916#2]
i tried several games and it suffer short lagspike in every load. dunno why i allready tried different cusrom. and i suspect it was kernel gpu driver but dunno and i just want to report this. btw freezing occurs when the game load and having slight shadow in screen border. (freezing in meaning it take a lot of time and loading animation didnt move at all while audio still playing)
tested on PUBGM. btw im using Z00T and lineage15 based cusrom.
(hardware? snapdragon615 /adreno405)

**Comment by theimpulson** [comment]
First of all, the board platform is 8916. Lags are normal if you play games like PUBGM that too on 8.x and greater. My builds have HWC2 as default display adapter which might be a reason as well. 

However, Adding back input boost in the kernel will be a nice idea as per me to fix this issue. I will do that. Maybe that will improve performance.

**Comment by AkagiShiroe** [comment]
thanks for trying to help sinnce the issue was only severe freezing on loading screen. mostly on Unity/UE based android games. if you push commit illtry to test it and report the result later.
i notice it since the freeze happen when a certain element loaded(like ui seriously do i need to wait 8 sec to see a texture show? and game need to load 5 more texture after that. i know we had we had gpu so no complain.)

**Comment by theimpulson** [comment]
I will push commits in a few hours. Also about your platform issue, check this:

https://github.com/theimpulson/android_device_asus_msm8916-common/blob/6e901eed6aef8111fa26a53a69543f73623d3a56/BoardConfigCommon.mk#L39

**Comment by AkagiShiroe** [comment]
i trried to modify my current rom by changing that line to msm8939 but no luck on it(stuck on ASUS logo).

**Comment by AkagiShiroe** [comment]
https://youtu.be/pC3UMQFpiSM
thia is how slow to load a single texture (i dump it and that texture was 2048*2048 resolution). and every game instances load are like 6 texture like this + some UI which is also 2k. game alao load additional effect texture dynamically.
the result was took me 4 minutes to load a stage whih normally in other devices and emulator was around a minutes. dunno what the cause. maybe i should downgrade my gpu driver to v140 but i dont want to use  MM rom.

**Comment by theimpulson** [comment]
I will be doing a rebase and work on a new source. Therefore, archiving this repo.
